language: go

go:
  - "1.14.x"

services:
  - docker

before_install:
  - tar -czf examples/sampleapp.tar.gz -C examples/ sampleapp

install:
  - go build -o dce-go-linux-amd64 dce/main.go
  - docker-compose up -d

script:
  - go run examples/docker-compose/create.go
  - go run examples/docker-compose/kill.go
